TTS_MODEL_NAME = "vits_tts"
SE_MODEL_NAME = "speaker_encoder"
WHISPER_LARGE_MODEL_NAME = "whisper_large"

DEFAULT_TTS_GRPC_API_URL = "0.0.0.0:8080"
DEFAULT_ASR_GRPC_API_URL = "0.0.0.0:8085"

SPEAKER_EMBEDDING_SIZE = 512
